---
title: "Project 1: Wrangling & Exploratory Data Analysis"
author: "Derek Sung DAS5374"
date: "2020-10-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

#### 1. Introduction

The two datasets used for this data analysis consist of data on mass shootings in 2019 and gun ownership in 2019 by state. This data was sourced from Statista and GunViolenceArchive, respectively. This data analysis will test to see if there are any potential associations between these two variables. If more guns are in circulation in a given population, one might expect a higher occurence of mass shootings. This association is particularly of interest since the state of Texas has the highest gun ownership in the country and as the number continues to increase, one might be concerned about the statistical probability of mass shootings associated with this number. 

#### 2. Tidying: Rearranging Wide/Long

```{R}
library(tidyverse)
library(tidyr)
library(dplyr)
guns <- read.csv("guns.csv")
deaths <- read.csv("deaths.csv")
deaths <- deaths %>% pivot_longer(5:6, names_to="condition", values_to="hurt")
deaths <- deaths %>% pivot_wider(names_from="condition", values_from="hurt")
```
The 'deaths' dataset containing information on mass shootings was tidied to make the two columns, consisting of number of people killed and the number of people injured, into one column. This groups killings and injuries into the same category of people who are hurt in general. However, for the purposes of simplying code later, this tidying will be undone and returned to the original format. 

#### 3. Joining/Merging

```{R}
both <- full_join(deaths, guns)
both <- both %>% rename(killed=X..Killed, injured=X..Injured, guns.per.capita=X..of.guns.per.capita, guns.registered=X..of.guns.registered)
both <- both %>% mutate(hurt=(killed+injured)) %>% select(-killed,-injured)
```
A full join keeps all rows from both datasets and inserts NAs where this is missing information, which is what we wanted since we did not want to lose any data. In this case, there are 12 rows in the combined dataset with NAs. These 12 datasets have NAs because there were no mass shootings in these 12 states.

#### 3. Wrangling

```{R}
both$State <- replace(both$State, both$State=="District of Columbia", "Washington D.C.")
both$State <- as.character(both$State)
both$hurt <- as.integer(both$hurt)
both$guns.per.capita <- as.integer(both$guns.per.capita)
both$guns.registered<- as.integer(both$guns.registered)

both %>% select(State, guns.per.capita) %>% arrange(desc(guns.per.capita))
both %>% select(State, guns.registered) %>% arrange(desc(guns.registered))

both %>% group_by(State) %>% summarize(n=n()) %>% arrange(desc(n))

both %>% mutate(hurtpergun=(hurt)/guns.per.capita) %>% arrange(desc(hurtpergun))

both %>% filter(State=="Texas")

both %>% summarize(mean_gunsreg=mean(guns.registered,na.rm=T), n_rows=n(), n_states= n_distinct(State), var=var(guns.per.capita,na.rm=T), quant=quantile(guns.registered,na.rm=T, .75), min=min(guns.registered,na.rm=T), max=max(guns.registered,na.rm=T), sd=sd(guns.registered,na.rm=T), med=median(hurt,na.rm=T), cor=cor(hurt,guns.registered, use="pair"))


both %>% group_by(State) %>% summarize(mean_gunsreg=mean(guns.registered,na.rm=T), n_rows=n(), n_states= n_distinct(State), var=var(guns.per.capita,na.rm=T), quant=quantile(guns.registered,na.rm=T, .75), min=min(guns.registered,na.rm=T), max=max(guns.registered,na.rm=T), sd=sd(guns.registered,na.rm=T), sum=sum(hurt,na.rm=T), cor=cor(hurt,guns.per.capita, use="pair"))
```
After tidying and joining both datasets, a few column titles were renamed for a better appearance. Then, in one dataset, the state of Washington D.C. was named as District of Columbia so that was changed to be consistent in state names. Finally, the 'States' column was formatted into "characters" intead of "factors" for data statistics. Firstly, states were arranged by descending guns per capita with Wyoming having the most amount of guns with 229.24 per 100,000 people. States were also arranged by descending guns registered with Texas having the most guns registered of 588696. Next, states were grouped together and then the total occurence of mass shootings was summed together and arranged by descending order with California having the most amount of mass shootings of 98. A new variable of 'hurtpergun' was generated by dividing 'hurt' by 'guns.per.capita'. Then finally, the data was filtered to show only the mass shootings that occured in the state of Texas.

Summary statistics was conducted on the data showing the mean guns registered of 190084.4, 430 total number of rows, 51 number of distinct states and the federal district of Washington D.C. , variance between guns per capita of 176.84, 1st quantile of guns registered of 236377, minimum value of guns registered of 4852, maximum value of guns registered of 588696, standard deviation of guns registered of 148051.2, median hurt of 465, and the correlation between people hurt and guns registered of 0.19. These same summary statistics were conducted again after grouping by state. 


#### 4. Visualizing
```{R}
library(ggplot2)
cormat <- both %>% select_if(is.numeric) %>% cor(use="pair")
tidycor <- cormat %>% as.data.frame %>% rownames_to_column("var1") %>% pivot_longer(-1,names_to="var2",values_to="correlation")
tidycor %>% ggplot(aes(var1,var2,fill=correlation)) + geom_tile() + scale_fill_gradient2(low="red",mid="white",high="blue") + geom_text(aes(label=round(correlation,2)),color = "black", size = 4) + theme(axis.text.x = element_text(angle = 90, hjust=1)) + coord_fixed() 

both %>% ggplot(aes(State, guns.registered)) + geom_bar(aes(fill=State),stat="summary") + theme_classic() + theme(axis.text.x = element_text(angle=60, hjust=1), legend.position="none") + geom_point(aes(size=hurt)) + ylab("# of Guns Registered") + xlab("State") + ggtitle("Number of Guns Registered and People Hurt per State in 2019")

both <- both %>% group_by(State) %>% mutate(n_rows=n())
both %>% ggplot(aes(x=guns.registered, fill=n_rows)) + geom_histogram(aes(fill="red"),bin=50) + geom_smooth(aes(y=guns.per.capita)) + ylab("# of Mass Shooting") + xlab("# of Guns Registered") + theme_classic() + theme(legend.position="none") + ggtitle("Number of Mass Shootings by Number of Guns Registered by State", subtitle = "with Guns per Capita Trendline")
```
The first plot is a correlation heatmap of all variables of the dataset. Rank and guns per capita had the highest correlation of -0.66. However, these variables were already pre-associated as the rank variable was based upon high to low guns per capita. Hurt and guns registered had the second highest correlation of 0.16. This is not a strong correlation and thus one can not say these two variables are associated.

The second plot is a bargraph that shows the number of guns registered for each state and the number of people hurt in each state, scaled in proportion to the total number of people hurt in 2019. In general, we can see that most states that have a higher number of guns registered have a higher number of people hurt. Specifically, if we look Texas and California that have some of the highest numbers of guns registered, we can see that they have the most people hurt in the country.

The third plot is a histogram that shows the number of mass shootings by number of guns registered. There is also a trendline that shows the number of guns per capita. There is a rough trend that the less number of guns registered and guns per capita, the fewer number of mass shootings there are. With the exception of the right most data point of Texas with the most number of guns registered, one could argue that there is an expontential relationship between number of guns registered and number of mass shootings. 

#### 5. Dimensionality Reduction
```{R}
library(cluster)
both2 <- both %>% na.omit %>% select(hurt, guns.per.capita, guns.registered) %>% as.data.frame()

sil_width<-vector()

for(i in 2:10){  
  pam_fit <- pam(both2, k = i)  
  sil_width[i] <- pam_fit$silinfo$avg.width  
}

ggplot()+geom_line(aes(x=1:10,y=sil_width))+scale_x_continuous(name="k",breaks=1:10)

pam1 <- both2 %>% pam(k=10)
pamclust <- both2 %>% mutate(cluster=as.factor(pam1$clustering))

library(plotly)
pamclust%>%plot_ly(x= ~hurt,  y = ~guns.per.capita, z = ~guns.registered, color= ~cluster, type = "scatter3d", mode = "markers")

pamclust %>% group_by(cluster) %>% summarize_if(is.numeric,mean)
both%>%slice(pam1$id.med)
plot(pam1, which=2)
```
A PAM clustering was conducted on the variables 'hurt', 'guns.per.capita', and 'guns.registered'. First we chose the number of clusters based upon average silhouette width because the higher the silhouette width is the better as clusters are more cohesive and more separated. Looking at the plot, we see that 10 clusters is the best. After clustering the data, we can see that the clusters are relatively separated with cluster 5 being those with a large number of guns registered and cluster 6 being those with a small number of guns registered. We also found the final medoids of our clusters with the state of New Jersey being representative of cluster 1 and the state of California being representative of cluster 10. With an average silhouette width of 0.8, we can say that a strong structure has been found. 

